import { Shop, Customer, Booking, Review, Queue, Service, OpeningHours, Employee, StylistPerformance, FinancialReport, DateRange, UserRole, OwnerDashboard, RefundRequest, RefundStatus, CustomerFeedback, FeedbackType, CustomerSuccessMetrics, Product, ProductCategory, CustomerTag, MembershipLevel, PurchaseVIPLevel, StoredValueLevel, BenefitType, StoredValueTxType, Settlement, SatisfactionSurvey, MembershipBenefit, PurchaseVIPPlan, StoredValuePlan, MemberBenefitRecord, StoredValueTransaction, ReferralRecord, CustomerProfile, HaircutStylePreference, HairColorPreference, PermColorPreference, TreatmentPreference, HairType, HairLength, VisitFrequency, BudgetRange, CommunicationStyle, ExtraServicePreference, VisitTimePreference, CustomerVisitRecord, ShopReview, StylistReview, FollowUpRecord } from './types';

const generateId = () => Math.random().toString(36).substr(2, 9);

const defaultOpeningHours: OpeningHours = {
  monday: { open: '09:00', close: '21:00', isOpen: true },
  tuesday: { open: '09:00', close: '21:00', isOpen: true },
  wednesday: { open: '09:00', close: '21:00', isOpen: true },
  thursday: { open: '09:00', close: '21:00', isOpen: true },
  friday: { open: '09:00', close: '22:00', isOpen: true },
  saturday: { open: '10:00', close: '22:00', isOpen: true },
  sunday: { open: '10:00', close: '20:00', isOpen: true },
};

export const shopPasswords: Record<string, string> = {
  'shop1': '123456',
};

export const stylistPasswords: Record<string, string> = {
  'e1': '123456',
  'e2': '123456',
  'e3': '123456',
};

export const ceoPasswords: Record<string, string> = {
  'ceo1': '123456',
};

export const csPasswords: Record<string, string> = {
  'cs1': '123456',
};

export const managerPasswords: Record<string, string> = {
  'mgr1': '123456',
};

export const mockShops: Shop[] = [
  {
    id: 'shop1',
    name: '皓诗形象设计',
    description: '专业剪发、烫染护理，让您拥有时尚发型',
    address: '青岛市城阳区流亭街道城中城购物广场2号门',
    latitude: 36.2667,
    longitude: 120.4167,
    phone: '13800138001',
    images: [
      'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=400&h=300&fit=crop',
      'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=400&h=300&fit=crop',
    ],
    services: [
      { id: 's1', name: '精剪', price: 68, duration: 30, description: '专业发型设计' },
      { id: 's2', name: '烫染套餐', price: 388, duration: 120, description: '染发+烫发' },
      { id: 's3', name: '护理', price: 168, duration: 60, description: '深层护理' },
    ],
    employees: [
      {
        id: 'e1', name: '李明', phone: '13900000011', avatar: '', title: '首席发型师',
        rating: 4.9, skillValue: 4.9, reviewCount: 328, totalServices: 1250,
        isActive: true, specialty: '精剪、烫染', role: UserRole.STYLIST,
        tags: ['日系短发', '男士油头', '质感烫'],
        weeklyRevenue: 6800,
      },
      {
        id: 'e2', name: '王芳', phone: '13900000012', avatar: '', title: '资深发型师',
        rating: 4.7, skillValue: 4.7, reviewCount: 215, totalServices: 890,
        isActive: true, specialty: '护理、造型', role: UserRole.STYLIST,
        tags: ['深层护理', '女士造型', '染发'],
        weeklyRevenue: 5200,
      },
      {
        id: 'e3', name: '张伟', phone: '13900000013', avatar: '', title: '发型师',
        rating: 4.5, skillValue: 4.5, reviewCount: 168, totalServices: 620,
        isActive: true, specialty: '精剪', role: UserRole.STYLIST,
        tags: ['男士剪发', '快剪'],
        weeklyRevenue: 3600,
      },
      { id: 'ceo1', name: '夏总', phone: '13900000100', avatar: '', title: 'CEO/老板', rating: 5.0, isActive: true, specialty: '店铺管理', role: UserRole.CEO },
      { id: 'cs1', name: '刘客服', phone: '13900000101', avatar: '', title: '客服专员', rating: 4.8, isActive: true, specialty: '客户回访/维护', role: UserRole.CUSTOMER_SERVICE },
      { id: 'mgr1', name: '张店长', phone: '13900000102', avatar: '', title: '店长', rating: 4.7, isActive: true, specialty: '店铺运营', role: UserRole.SHOP_MANAGER },
    ],
    products: generateMockProducts('shop1'),
    openingHours: defaultOpeningHours,
    level: 'excellent',
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'shop2',
    name: '匠人理发',
    description: '传统与现代结合的理发技艺',
    address: '北京市海淀区中关村大街1号',
    latitude: 39.9892,
    longitude: 116.3174,
    phone: '13800138002',
    images: [
      'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=400&h=300&fit=crop',
    ],
    services: [
      { id: 's1', name: '男士剪发', price: 58, duration: 25 },
      { id: 's2', name: '女士剪发', price: 88, duration: 40 },
      { id: 's3', name: '渐变剪', price: 98, duration: 45 },
    ],
    employees: [
      { id: 'e1', name: '陈师傅', avatar: '', title: '首席造型师', rating: 4.8, isActive: true, specialty: '渐变剪、油头' },
      { id: 'e2', name: '刘师傅', avatar: '', title: '资深发型师', rating: 4.6, isActive: true, specialty: '男士剪发' },
    ],
    products: generateMockProducts('shop2'),
    openingHours: defaultOpeningHours,
    level: 'good',
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'shop3',
    name: '潮人理发店',
    description: '时尚潮流发型设计中心',
    address: '北京市西城区西单北大街120号',
    latitude: 39.9142,
    longitude: 116.3774,
    phone: '13800138003',
    images: [
      'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=400&h=300&fit=crop',
    ],
    services: [
      { id: 's1', name: '潮流剪发', price: 128, duration: 45 },
      { id: 's2', name: '接发', price: 588, duration: 180 },
    ],
    employees: [
      { id: 'e1', name: 'Tony老师', avatar: '', title: '创意总监', rating: 4.7, isActive: true, specialty: '潮流剪发、接发' },
      { id: 'e2', name: 'Kevin', avatar: '', title: '发型设计师', rating: 4.4, isActive: true, specialty: '潮流造型' },
    ],
    products: generateMockProducts('shop3'),
    openingHours: defaultOpeningHours,
    level: 'average',
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockCustomers: Customer[] = [
  {
    id: 'cust1',
    name: '张三',
    phone: '13900000001',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face',
    gender: 'male',
    age: 32,
    tags: [CustomerTag.HAIRCUT, CustomerTag.PERM, CustomerTag.FREQUENT, CustomerTag.VIP],
    visitCount: 28,
    totalSpent: 5680,
    purchaseVIPLevel: PurchaseVIPLevel.SILVER,
    purchaseVIPExpiresAt: new Date(Date.now() + 180 * 86400000),
    storedValueLevel: StoredValueLevel.STORE_2000,
    storedValueBalance: 2000,
    withdrawableReferralAmount: 120,
    membershipLevel: MembershipLevel.PREMIUM,
    balance: 2000,
    points: 568,
    joinedAt: new Date(Date.now() - 365 * 86400000),
    lastVisitAt: new Date(Date.now() - 7 * 86400000),
    birthday: new Date('1992-05-15'),
    preferences: ['精剪', '烫染'],
    isStockholder: true,
    stockholderSince: new Date(Date.now() - 180 * 86400000),
    referralBonusRate: 0.05,
    referralEarnings: 1280,
    source: '朋友推荐',
    servedByStylistIds: ['e1', 'e2'],
    totalSaved: 568,
    daysSinceLastVisit: 7,
    churnRisk: 'low',
    profile: {
      id: 'prof1',
      customerId: 'cust1',
      updatedBy: 'e1',
      updatedByName: '李明',
      updatedAt: new Date(Date.now() - 7 * 86400000),
      haircutStyles: [HaircutStylePreference.SHORT, HaircutStylePreference.UNDERCUT],
      hairColors: [HairColorPreference.NATURAL_BLACK, HairColorPreference.BROWN],
      permColors: [PermColorPreference.BIG_CURL, PermColorPreference.DIGITAL_PERM],
      treatments: [TreatmentPreference.DEEP_TREATMENT, TreatmentPreference.KERATIN],
      hairType: HairType.NORMAL,
      hairLength: HairLength.SHORT,
      visitFrequency: VisitFrequency.EVERY_MONTH,
      budgetRange: BudgetRange.R300_500,
      communicationStyle: CommunicationStyle.CHATTY,
      extraServices: [ExtraServicePreference.HEAD_MASSAGE, ExtraServicePreference.HOT_TOWEL],
      visitTimes: [VisitTimePreference.WEEKEND, VisitTimePreference.AFTERNOON],
      notes: '客户喜欢时尚造型，对发型要求较高',
      allergies: '无',
      productsUsed: ['专业防脱洗发水', '深层滋养发膜'],
      createdAt: new Date(Date.now() - 30 * 86400000),
    },
    visitRecords: [
      {
        id: 'vr1',
        customerId: 'cust1',
        shopId: 'shop1',
        bookingId: 'book1',
        stylistId: 'e1',
        stylistName: '李明',
        serviceIds: ['s1', 's2'],
        serviceNames: ['精剪', '烫染套餐'],
        products: [{ id: 'p1', name: '专业防脱洗发水', quantity: 1 }],
        totalAmount: 456,
        paymentMethod: 'wechat',
        checkInTime: new Date(Date.now() - 7 * 86400000),
        notes: '客户很满意，预约了下次',
        createdAt: new Date(Date.now() - 7 * 86400000),
      },
      {
        id: 'vr2',
        customerId: 'cust1',
        shopId: 'shop1',
        stylistId: 'e2',
        stylistName: '王芳',
        serviceIds: ['s3'],
        serviceNames: ['护理'],
        totalAmount: 168,
        paymentMethod: 'balance',
        checkInTime: new Date(Date.now() - 30 * 86400000),
        notes: '',
        createdAt: new Date(Date.now() - 30 * 86400000),
      },
    ],
  },
  {
    id: 'cust2',
    name: '李四',
    phone: '13900000002',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face',
    gender: 'female',
    age: 28,
    tags: [CustomerTag.COLOR, CustomerTag.TREATMENT, CustomerTag.NEW],
    visitCount: 8,
    totalSpent: 1860,
    purchaseVIPLevel: PurchaseVIPLevel.BRONZE,
    purchaseVIPExpiresAt: new Date(Date.now() + 200 * 86400000),
    storedValueLevel: StoredValueLevel.STORE_500,
    storedValueBalance: 500,
    withdrawableReferralAmount: 0,
    membershipLevel: MembershipLevel.REGULAR,
    balance: 500,
    points: 186,
    joinedAt: new Date(Date.now() - 90 * 86400000),
    lastVisitAt: new Date(Date.now() - 3 * 86400000),
    birthday: new Date('1998-08-22'),
    preferences: ['染发', '护理'],
    isStockholder: false,
    source: '路过进店',
    servedByStylistIds: ['e2'],
    totalSaved: 0,
    daysSinceLastVisit: 3,
    churnRisk: 'low',
    profile: {
      id: 'prof2',
      customerId: 'cust2',
      updatedBy: 'e2',
      updatedByName: '王芳',
      updatedAt: new Date(Date.now() - 3 * 86400000),
      haircutStyles: [HaircutStylePreference.MEDIUM, HaircutStylePreference.LAYERED],
      hairColors: [HairColorPreference.BROWN, HairColorPreference.GOLD],
      permColors: [PermColorPreference.BIG_CURL],
      treatments: [TreatmentPreference.MOISTURE, TreatmentPreference.OIL_TREATMENT],
      hairType: HairType.DRY,
      hairLength: HairLength.MEDIUM,
      visitFrequency: VisitFrequency.EVERY_2_MONTHS,
      budgetRange: BudgetRange.R100_300,
      communicationStyle: CommunicationStyle.QUIET,
      extraServices: [ExtraServicePreference.HAIR_WASH],
      visitTimes: [VisitTimePreference.EVENING, VisitTimePreference.WEEKDAY],
      notes: '客户喜欢安静的服务环境',
      allergies: '对某些染发剂过敏',
      productsUsed: ['深层滋养发膜'],
      createdAt: new Date(Date.now() - 60 * 86400000),
    },
    visitRecords: [
      {
        id: 'vr3',
        customerId: 'cust2',
        shopId: 'shop1',
        stylistId: 'e2',
        stylistName: '王芳',
        serviceIds: ['s2'],
        serviceNames: ['烫染套餐'],
        totalAmount: 388,
        paymentMethod: 'alipay',
        checkInTime: new Date(Date.now() - 3 * 86400000),
        notes: '染发效果很好',
        createdAt: new Date(Date.now() - 3 * 86400000),
      },
    ],
  },
  {
    id: 'cust3',
    name: '王五',
    phone: '13900000003',
    avatar: 'https://images.unsplash.com/photo-150703211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face',
    gender: 'male',
    age: 45,
    tags: [CustomerTag.HAIRCUT, CustomerTag.WIG, CustomerTag.FREQUENT],
    visitCount: 45,
    totalSpent: 8920,
    purchaseVIPLevel: PurchaseVIPLevel.DIAMOND,
    purchaseVIPExpiresAt: new Date(Date.now() + 300 * 86400000),
    storedValueLevel: StoredValueLevel.STORE_5000,
    storedValueBalance: 5000,
    withdrawableReferralAmount: 800,
    membershipLevel: MembershipLevel.STOCKHOLDER,
    balance: 5000,
    points: 892,
    joinedAt: new Date(Date.now() - 730 * 86400000),
    lastVisitAt: new Date(Date.now() - 2 * 86400000),
    birthday: new Date('1981-11-30'),
    preferences: ['精剪', '假发'],
    isStockholder: true,
    stockholderSince: new Date(Date.now() - 365 * 86400000),
    referralBonusRate: 0.05,
    referralEarnings: 3560,
    source: '网络搜索',
    servedByStylistIds: ['e1', 'e3'],
    totalSaved: 1784,
    daysSinceLastVisit: 2,
    churnRisk: 'low',
    profile: {
      id: 'prof3',
      customerId: 'cust3',
      updatedBy: 'e1',
      updatedByName: '李明',
      updatedAt: new Date(Date.now() - 2 * 86400000),
      haircutStyles: [HaircutStylePreference.SHORT, HaircutStylePreference.PIXIE],
      hairColors: [HairColorPreference.NATURAL_BLACK],
      permColors: [PermColorPreference.NO_PERM],
      treatments: [TreatmentPreference.SCALP_CARE],
      hairType: HairType.OILY,
      hairLength: HairLength.SHORT,
      visitFrequency: VisitFrequency.EVERY_2_WEEKS,
      budgetRange: BudgetRange.R500_1000,
      communicationStyle: CommunicationStyle.PROFESSIONAL,
      extraServices: [ExtraServicePreference.BEARD_TRIM, ExtraServicePreference.HOT_TOWEL],
      visitTimes: [VisitTimePreference.MORNING],
      notes: 'VIP客户，服务要特别关照',
      allergies: '无',
      productsUsed: ['专业防脱洗发水', '强力定型发胶'],
      createdAt: new Date(Date.now() - 100 * 86400000),
    },
    visitRecords: [
      {
        id: 'vr4',
        customerId: 'cust3',
        shopId: 'shop1',
        stylistId: 'e1',
        stylistName: '李明',
        serviceIds: ['s1'],
        serviceNames: ['精剪'],
        products: [{ id: 'p3', name: '强力定型发胶', quantity: 2 }],
        totalAmount: 244,
        paymentMethod: 'balance',
        checkInTime: new Date(Date.now() - 2 * 86400000),
        notes: '',
        createdAt: new Date(Date.now() - 2 * 86400000),
      },
      {
        id: 'vr5',
        customerId: 'cust3',
        shopId: 'shop1',
        stylistId: 'e3',
        stylistName: '张伟',
        serviceIds: ['s1'],
        serviceNames: ['精剪'],
        totalAmount: 68,
        paymentMethod: 'cash',
        checkInTime: new Date(Date.now() - 14 * 86400000),
        notes: '',
        createdAt: new Date(Date.now() - 14 * 86400000),
      },
    ],
  },
  {
    id: 'cust4',
    name: '赵六',
    phone: '13900000004',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop&crop=face',
    gender: 'female',
    age: 25,
    tags: [CustomerTag.PRODUCTS, CustomerTag.NEW],
    visitCount: 3,
    totalSpent: 456,
    purchaseVIPLevel: PurchaseVIPLevel.REGULAR,
    storedValueLevel: StoredValueLevel.NONE,
    storedValueBalance: 0,
    withdrawableReferralAmount: 0,
    membershipLevel: MembershipLevel.REGULAR,
    balance: 0,
    points: 46,
    joinedAt: new Date(Date.now() - 30 * 86400000),
    lastVisitAt: new Date(Date.now() - 1 * 86400000),
    birthday: new Date('2001-03-12'),
    preferences: ['洗护产品'],
    isStockholder: false,
    source: '老客户介绍',
    servedByStylistIds: ['e2'],
    totalSaved: 0,
    daysSinceLastVisit: 1,
    churnRisk: 'medium',
    profile: {
      id: 'prof4',
      customerId: 'cust4',
      updatedBy: 'e2',
      updatedByName: '王芳',
      updatedAt: new Date(Date.now() - 1 * 86400000),
      haircutStyles: [HaircutStylePreference.LONG, HaircutStylePreference.BANGS],
      hairColors: [HairColorPreference.FASHION_COLOR],
      permColors: [PermColorPreference.SMALL_CURL],
      treatments: [TreatmentPreference.NO_TREATMENT],
      hairType: HairType.NORMAL,
      hairLength: HairLength.LONG,
      visitFrequency: VisitFrequency.IRREGULAR,
      budgetRange: BudgetRange.UNDER_100,
      communicationStyle: CommunicationStyle.NO_PREFERENCE,
      extraServices: [ExtraServicePreference.NO_EXTRA],
      visitTimes: [VisitTimePreference.WEEKEND],
      notes: '年轻客户，喜欢尝试新潮发型',
      allergies: '无',
      productsUsed: ['深层滋养发膜'],
      createdAt: new Date(Date.now() - 20 * 86400000),
    },
    visitRecords: [
      {
        id: 'vr6',
        customerId: 'cust4',
        shopId: 'shop1',
        stylistId: 'e2',
        stylistName: '王芳',
        serviceIds: ['s1'],
        serviceNames: ['精剪'],
        products: [{ id: 'p2', name: '深层滋养发膜', quantity: 1 }],
        totalAmount: 196,
        paymentMethod: 'wechat',
        checkInTime: new Date(Date.now() - 1 * 86400000),
        notes: '第一次来店体验',
        createdAt: new Date(Date.now() - 1 * 86400000),
      },
    ],
  },
  {
    id: 'cust5',
    name: '孙七',
    phone: '13900000005',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100&fit=crop&crop=face',
    gender: 'male',
    age: 38,
    tags: [CustomerTag.HAIRCUT, CustomerTag.PERM, CustomerTag.COLOR, CustomerTag.FREQUENT],
    visitCount: 35,
    totalSpent: 6780,
    purchaseVIPLevel: PurchaseVIPLevel.GOLD,
    purchaseVIPExpiresAt: new Date(Date.now() + 120 * 86400000),
    storedValueLevel: StoredValueLevel.STORE_1000,
    storedValueBalance: 1500,
    withdrawableReferralAmount: 60,
    membershipLevel: MembershipLevel.PREMIUM,
    balance: 1500,
    points: 678,
    joinedAt: new Date(Date.now() - 180 * 86400000),
    lastVisitAt: new Date(Date.now() - 5 * 86400000),
    birthday: new Date('1988-07-08'),
    preferences: ['精剪', '烫染', '染发'],
    isStockholder: false,
    source: '朋友推荐',
    servedByStylistIds: ['e1', 'e2', 'e3'],
    totalSaved: 678,
    daysSinceLastVisit: 5,
    churnRisk: 'low',
    profile: {
      id: 'prof5',
      customerId: 'cust5',
      updatedBy: 'e1',
      updatedByName: '李明',
      updatedAt: new Date(Date.now() - 5 * 86400000),
      haircutStyles: [HaircutStylePreference.MEDIUM, HaircutStylePreference.LAYERED],
      hairColors: [HairColorPreference.BROWN, HairColorPreference.RED],
      permColors: [PermColorPreference.BIG_CURL, PermColorPreference.DIGITAL_PERM],
      treatments: [TreatmentPreference.DEEP_TREATMENT],
      hairType: HairType.COLOR_TREATED,
      hairLength: HairLength.MEDIUM,
      visitFrequency: VisitFrequency.EVERY_MONTH,
      budgetRange: BudgetRange.R300_500,
      communicationStyle: CommunicationStyle.CHATTY,
      extraServices: [ExtraServicePreference.HEAD_MASSAGE],
      visitTimes: [VisitTimePreference.AFTERNOON, VisitTimePreference.EVENING],
      notes: '客户很健谈，喜欢边做边聊',
      allergies: '无',
      productsUsed: ['专业防脱洗发水', '深层滋养发膜', '强力定型发胶'],
      createdAt: new Date(Date.now() - 90 * 86400000),
    },
    visitRecords: [
      {
        id: 'vr7',
        customerId: 'cust5',
        shopId: 'shop1',
        stylistId: 'e1',
        stylistName: '李明',
        serviceIds: ['s1', 's2'],
        serviceNames: ['精剪', '烫染套餐'],
        totalAmount: 456,
        paymentMethod: 'wechat',
        checkInTime: new Date(Date.now() - 5 * 86400000),
        notes: '非常满意的服务',
        createdAt: new Date(Date.now() - 5 * 86400000),
      },
      {
        id: 'vr8',
        customerId: 'cust5',
        shopId: 'shop1',
        stylistId: 'e3',
        stylistName: '张伟',
        serviceIds: ['s1'],
        serviceNames: ['精剪'],
        totalAmount: 68,
        paymentMethod: 'alipay',
        checkInTime: new Date(Date.now() - 35 * 86400000),
        notes: '',
        createdAt: new Date(Date.now() - 35 * 86400000),
      },
    ],
  },
];

export const mockBookings: Booking[] = [
  {
    id: 'book1',
    shopId: 'shop1',
    customerId: 'cust1',
    serviceId: 's1',
    barberId: 'e1',
    barberName: '李明',
    scheduledTime: new Date(Date.now() + 3600000),
    status: 'confirmed',
    queueNumber: 3,
    serviceName: '精剪',
    price: 68,
    customerName: '张三',
    shopName: '风格美发沙龙',
  },
];

export const mockReviews: Review[] = [
  {
    id: 'rev1',
    shopId: 'shop1',
    customerId: 'cust1',
    bookingId: 'book1',
    serviceScore: 5,
    priceScore: 4,
    skillScore: 5,
    overallScore: 4.7,
    comment: '发型师技术很好，服务态度也很棒！',
    customerName: '张三',
    createdAt: new Date(Date.now() - 86400000),
  },
];

export const mockQueues: Queue[] = [
  {
    id: 'queue1',
    shopId: 'shop1',
    currentNumber: 1,
    estimatedWaitTime: 45,
    bookings: [mockBookings[0]],
  },
];

export const soundOptions = [
  { id: 'chime', name: '清脆铃声' },
  { id: 'bell', name: '传统铃铛' },
  { id: 'notify', name: '通知音' },
  { id: 'ding', name: '叮咚声' },
];

export function getMockStylistPerformance(
  stylistId: string,
  shopId: string
): StylistPerformance {
  const shop = mockShops.find(s => s.id === shopId);
  const stylist = shop?.employees.find(e => e.id === stylistId);

  const baseRevenue = stylist?.rating ? (stylist.rating * 500) : 2000;

  return {
    stylistId,
    stylistName: stylist?.name || '发型师',
    avatar: stylist?.avatar,
    revenue: {
      today: Math.floor(baseRevenue * 0.12),
      week: Math.floor(baseRevenue * 0.5),
      month: Math.floor(baseRevenue * 2),
      year: Math.floor(baseRevenue * 24),
    },
    services: {
      total: Math.floor(Math.random() * 50) + 20,
      byType: {
        '精剪': Math.floor(Math.random() * 30) + 10,
        '烫染': Math.floor(Math.random() * 15) + 5,
        '护理': Math.floor(Math.random() * 10) + 3,
      }
    },
    estimatedCommission: Math.floor(baseRevenue * 0.3),
    averageRating: stylist?.rating || 4.5,
  };
}

export function getMockFinancialReport(shopId: string): FinancialReport {
  const shop = mockShops.find(s => s.id === shopId);

  const baseRevenue = 50000;

  const topStylists = shop?.employees
    .filter(emp => emp.isActive)
    .map(emp => ({
      id: emp.id,
      name: emp.name,
      avatar: emp.avatar,
      revenue: Math.floor((emp.rating || 4.5) * 3000) + Math.floor(Math.random() * 2000),
      services: Math.floor(Math.random() * 50) + 20,
      rating: emp.rating || 4.5,
    }))
    .sort((a, b) => b.revenue - a.revenue) || [];

  return {
    revenue: {
      today: Math.floor(baseRevenue * 0.05) + Math.floor(Math.random() * 1000),
      week: Math.floor(baseRevenue * 0.3) + Math.floor(Math.random() * 5000),
      month: baseRevenue + Math.floor(Math.random() * 20000),
      year: baseRevenue * 12 + Math.floor(Math.random() * 100000),
    },
    services: {
      today: Math.floor(Math.random() * 20) + 5,
      week: Math.floor(Math.random() * 100) + 30,
      month: Math.floor(Math.random() * 400) + 100,
      year: Math.floor(Math.random() * 5000) + 1000,
    },
    averageTicket: {
      today: Math.floor(Math.random() * 100) + 150,
      week: Math.floor(Math.random() * 80) + 160,
      month: Math.floor(Math.random() * 70) + 170,
      year: Math.floor(Math.random() * 60) + 180,
    },
    topStylists,
  };
}

export function getDefaultDateRange(): DateRange {
  const today = new Date();
  const lastWeek = new Date(today);
  lastWeek.setDate(lastWeek.getDate() - 7);

  return {
    start: lastWeek,
    end: today,
  };
}

export function getOwnerDashboard(): OwnerDashboard {
  const baseRevenue = 150000;
  const baseServices = 800;
  const baseCustomers = 600;

  const shopStats = mockShops.map(shop => {
    const shopRevenue = Math.floor(baseRevenue * (0.3 + Math.random() * 0.2));
    return {
      shopId: shop.id,
      shopName: shop.name,
      revenue: shopRevenue,
      services: Math.floor(baseServices * (shopRevenue / baseRevenue)),
      customers: Math.floor(baseCustomers * (shopRevenue / baseRevenue)),
      employees: shop.employees.filter(e => e.isActive).length,
    };
  });

  const topStylists = mockShops.flatMap(shop =>
    shop.employees
      .filter(emp => emp.isActive)
      .map(emp => ({
        id: emp.id,
        name: emp.name,
        shopId: shop.id,
        shopName: shop.name,
        avatar: emp.avatar,
        revenue: Math.floor((emp.rating || 4.5) * 5000) + Math.floor(Math.random() * 3000),
        services: Math.floor(Math.random() * 60) + 30,
        rating: emp.rating || 4.5,
      }))
  ).sort((a, b) => b.revenue - a.revenue).slice(0, 10);

  return {
    totalRevenue: {
      today: Math.floor(baseRevenue * 0.04) + Math.floor(Math.random() * 2000),
      week: Math.floor(baseRevenue * 0.25) + Math.floor(Math.random() * 10000),
      month: baseRevenue + Math.floor(Math.random() * 50000),
      year: baseRevenue * 12 + Math.floor(Math.random() * 200000),
    },
    totalServices: {
      today: Math.floor(Math.random() * 40) + 15,
      week: Math.floor(Math.random() * 200) + 80,
      month: baseServices + Math.floor(Math.random() * 200),
      year: baseServices * 12 + Math.floor(Math.random() * 2000),
    },
    totalCustomers: {
      today: Math.floor(Math.random() * 30) + 10,
      week: Math.floor(Math.random() * 150) + 60,
      month: baseCustomers + Math.floor(Math.random() * 150),
      year: baseCustomers * 12 + Math.floor(Math.random() * 1500),
    },
    shopStats,
    topStylists,
  };
}

export const mockRefundRequests: RefundRequest[] = [
  {
    id: 'refund1',
    bookingId: 'booking1',
    customerId: 'customer1',
    customerName: '张三',
    shopId: 'shop1',
    shopName: '潮流造型',
    amount: 68,
    reason: '服务时间与预约不符，等待时间过长',
    status: RefundStatus.PENDING,
    createdAt: new Date(Date.now() - 86400000),
  },
  {
    id: 'refund2',
    bookingId: 'booking2',
    customerId: 'customer2',
    customerName: '李四',
    shopId: 'shop1',
    shopName: '潮流造型',
    amount: 128,
    reason: '发型师技术不满意',
    status: RefundStatus.APPROVED,
    createdAt: new Date(Date.now() - 172800000),
    processedAt: new Date(Date.now() - 86400000),
    processedBy: '店主',
    refundMethod: 'original',
  },
  {
    id: 'refund3',
    bookingId: 'booking3',
    customerId: 'customer3',
    customerName: '王五',
    shopId: 'shop2',
    shopName: '时尚发艺',
    amount: 88,
    reason: '临时有事无法到店',
    status: RefundStatus.COMPLETED,
    createdAt: new Date(Date.now() - 259200000),
    processedAt: new Date(Date.now() - 172800000),
    processedBy: '店长',
    refundMethod: 'original',
  },
];

export const mockCustomerFeedbacks: CustomerFeedback[] = [
  {
    id: 'feedback1',
    customerId: 'customer1',
    customerName: '张三',
    shopId: 'shop1',
    bookingId: 'booking1',
    type: FeedbackType.COMPLAINT,
    title: '服务态度问题',
    content: '发型师在服务过程中频繁接打电话，影响服务体验',
    status: 'pending',
    priority: 'high',
    createdAt: new Date(Date.now() - 43200000),
  },
  {
    id: 'feedback2',
    customerId: 'customer2',
    customerName: '李四',
    shopId: 'shop1',
    type: FeedbackType.SUGGESTION,
    title: '建议增加周末营业时间',
    content: '希望周末能延长营业时间到晚上10点，方便上班族',
    status: 'processing',
    priority: 'medium',
    createdAt: new Date(Date.now() - 86400000),
  },
  {
    id: 'feedback3',
    customerId: 'customer3',
    customerName: '王五',
    shopId: 'shop2',
    type: FeedbackType.PRAISE,
    title: '非常满意的服务',
    content: '发型师技术很好，服务态度也很棒，环境舒适',
    status: 'resolved',
    priority: 'low',
    createdAt: new Date(Date.now() - 172800000),
    resolvedAt: new Date(Date.now() - 86400000),
    resolvedBy: '店长',
    resolution: '感谢您的认可，我们会继续保持优质服务！',
  },
];

export function generateMockProducts(shopId: string): Product[] {
  return [
    {
      id: `p${shopId}_1`,
      shopId,
      name: '真人发丝假发 - 自然黑中长发',
      category: ProductCategory.WIG,
      price: 1280,
      originalPrice: 1580,
      description: '100%真人发丝，自然逼真，透气舒适，可烫可染',
      images: [
        'https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?w=400&h=400&fit=crop',
      ],
      stock: 50,
      sales: 128,
      isActive: true,
      rating: 4.8,
      reviewCount: 56,
      tags: ['热销', '新品'],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: `p${shopId}_2`,
      shopId,
      name: '高端假发 - 亚麻棕大波浪',
      category: ProductCategory.WIG,
      price: 2580,
      originalPrice: 3280,
      description: '高端定制，手织工艺，轻盈舒适，明星同款',
      images: [
        'https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=400&h=400&fit=crop',
      ],
      stock: 25,
      sales: 68,
      isActive: true,
      rating: 4.9,
      reviewCount: 32,
      tags: ['高端', '明星同款'],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: `p${shopId}_3`,
      shopId,
      name: '专业防脱洗发水 500ml',
      category: ProductCategory.HAIR_CARE,
      price: 168,
      originalPrice: 218,
      description: '蕴含生姜精华，有效防脱固发，滋养发根',
      images: [
        'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=400&h=400&fit=crop',
      ],
      stock: 200,
      sales: 356,
      isActive: true,
      rating: 4.7,
      reviewCount: 142,
      tags: ['热销', '防脱'],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: `p${shopId}_4`,
      shopId,
      name: '深层滋养发膜 300ml',
      category: ProductCategory.HAIR_CARE,
      price: 128,
      originalPrice: 168,
      description: '深度滋养，修复受损发质，让头发柔顺亮泽',
      images: [
        'https://images.unsplash.com/photo-1571875257727-256c39da4228?w=400&h=400&fit=crop',
      ],
      stock: 180,
      sales: 289,
      isActive: true,
      rating: 4.6,
      reviewCount: 98,
      tags: ['滋养', '修复'],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: `p${shopId}_5`,
      shopId,
      name: '强力定型发胶 500ml',
      category: ProductCategory.STYLING,
      price: 88,
      originalPrice: 128,
      description: '强力定型，持久不塌，清爽不粘腻',
      images: [
        'https://images.unsplash.com/photo-1616394584738-fc6e612e7169?w=400&h=400&fit=crop',
      ],
      stock: 150,
      sales: 423,
      isActive: true,
      rating: 4.5,
      reviewCount: 186,
      tags: ['热销', '定型'],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: `p${shopId}_6`,
      shopId,
      name: '专业美发剪刀套装',
      category: ProductCategory.TOOLS,
      price: 398,
      originalPrice: 498,
      description: '德国工艺，锋利耐用，专业发型师首选',
      images: [
        'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400&h=400&fit=crop',
      ],
      stock: 45,
      sales: 78,
      isActive: true,
      rating: 4.9,
      reviewCount: 45,
      tags: ['专业', '德国工艺'],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];
}

export function getCustomerSuccessMetrics(customerId: string): CustomerSuccessMetrics {
  const customer = mockCustomers.find(c => c.id === customerId);
  const bookings = mockBookings.filter(b => b.customerId === customerId);

  return {
    customerId,
    totalBookings: bookings.length,
    completedBookings: bookings.filter(b => b.status === 'completed').length,
    cancelledBookings: bookings.filter(b => b.status === 'cancelled').length,
    totalSpent: bookings
      .filter(b => b.status === 'completed')
      .reduce((sum, b) => sum + (b.price || 0), 0),
    averageRating: 4.5,
    lastVisitDate: bookings.length > 0 ? new Date(bookings[0].scheduledTime) : undefined,
    loyaltyPoints: Math.floor(Math.random() * 500) + 100,
    membershipLevel: ['regular', 'silver', 'gold', 'platinum'][Math.floor(Math.random() * 4)] as any,
    customerSince: new Date(Date.now() - Math.floor(Math.random() * 365) * 86400000),
  };
}

export const membershipBenefits: MembershipBenefit[] = [
  {
    level: MembershipLevel.REGULAR,
    discount: 1,
    pointsRate: 1,
    gifts: [],
    canBecomeStockholder: false,
  },
  {
    level: MembershipLevel.PREMIUM,
    discount: 0.9,
    pointsRate: 1.5,
    gifts: ['免费护理一次', '生日礼品'],
    canBecomeStockholder: true,
    referralBonusRate: 0.03,
  },
  {
    level: MembershipLevel.STOCKHOLDER,
    discount: 0.8,
    pointsRate: 2,
    gifts: ['专属发型师', '优先预约', '生日派对'],
    canBecomeStockholder: true,
    referralBonusRate: 0.05,
  },
];

// 购买型 VIP 会员计划
export const purchaseVIPPlans: PurchaseVIPPlan[] = [
  {
    level: PurchaseVIPLevel.REGULAR,
    name: '普通用户',
    price: 0,
    period: '长期',
    discount: 1,
    pointsRate: 1,
    benefits: ['按店内正常价格消费'],
    color: 'gray',
  },
  {
    level: PurchaseVIPLevel.BRONZE,
    name: '普卡 VIP',
    price: 29,
    period: '年',
    discount: 0.88,
    pointsRate: 1.2,
    benefits: ['全场 8.8 折（假发除外）', '消费满 59 元送洗发水', '积分 1.2 倍'],
    color: 'orange',
  },
  {
    level: PurchaseVIPLevel.SILVER,
    name: '银卡 VIP',
    price: 59,
    period: '年',
    discount: 0.78,
    pointsRate: 1.5,
    benefits: ['全场 7.8 折（假发除外）', '消费满 59 元送洗发水+护发素', '积分 1.5 倍', '每次消费送饮品'],
    color: 'blue',
  },
  {
    level: PurchaseVIPLevel.GOLD,
    name: '金卡 VIP',
    price: 79,
    period: '年',
    discount: 0.68,
    pointsRate: 2,
    benefits: ['全场 6.8 折（假发除外）', '消费满 59 元送洗发水+护发素', '积分 2 倍', '每次消费送饮品', '不满意重做'],
    color: 'yellow',
  },
  {
    level: PurchaseVIPLevel.DIAMOND,
    name: '钻石 VIP',
    price: 99,
    period: '年',
    discount: 0.58,
    pointsRate: 3,
    benefits: ['全场 5.8 折（假发除外）', '消费满 59 元送洗发水+护发素', '积分 3 倍', '每次消费送饮品', '不满意重做', '单次免费剪发一次'],
    color: 'purple',
  },
];

// 储值会员计划
export const storedValuePlans: StoredValuePlan[] = [
  {
    level: StoredValueLevel.NONE,
    name: '未储值',
    amount: 0,
    discount: 1,
    pointsRate: 1,
    benefits: ['可使用现金/微信/支付宝支付'],
    color: 'gray',
  },
  {
    level: StoredValueLevel.STORE_500,
    name: '储值卡',
    amount: 500,
    discount: 0.9,
    pointsRate: 1.1,
    benefits: ['储值 500 元', '折上折再享 9 折', '积分 1.1 倍'],
    color: 'green',
  },
  {
    level: StoredValueLevel.STORE_1000,
    name: '安心卡',
    amount: 1000,
    discount: 0.85,
    pointsRate: 1.3,
    benefits: ['储值 1000 元', '折上折再享 8.5 折', '积分 1.3 倍'],
    color: 'cyan',
  },
  {
    level: StoredValueLevel.STORE_2000,
    name: '顺心卡',
    amount: 2000,
    discount: 0.8,
    pointsRate: 1.5,
    benefits: ['储值 2000 元', '折上折再享 8 折', '积分 1.5 倍'],
    color: 'indigo',
  },
  {
    level: StoredValueLevel.STORE_5000,
    name: '随心卡',
    amount: 5000,
    discount: 0.7,
    pointsRate: 2,
    benefits: ['储值 5000 元', '折上折再享 7 折', '积分 2 倍'],
    color: 'red',
  },
];

// 会员权益记录（可核销）
export const mockMemberBenefitRecords: MemberBenefitRecord[] = [
  {
    id: 'benefit1',
    customerId: 'cust1',
    type: BenefitType.SHAMPOO,
    name: '洗发水',
    description: '单次消费满 59 元赠送',
    status: 'available',
    grantedAt: new Date(Date.now() - 7 * 86400000),
    expiresAt: new Date(Date.now() + 83 * 86400000),
  },
  {
    id: 'benefit2',
    customerId: 'cust3',
    type: BenefitType.FREE_HAIRCUT,
    name: '免费剪发一次',
    description: '钻石 VIP 专属权益',
    status: 'available',
    grantedAt: new Date(Date.now() - 300 * 86400000),
    expiresAt: new Date(Date.now() + 65 * 86400000),
  },
];

// 储值余额流水
export const mockStoredValueTransactions: StoredValueTransaction[] = [
  {
    id: 'svtx1',
    customerId: 'cust1',
    type: StoredValueTxType.RECHARGE,
    amount: 2000,
    balanceAfter: 2000,
    referralPortion: 0,
    note: '开通顺心卡',
    createdAt: new Date(Date.now() - 60 * 86400000),
  },
  {
    id: 'svtx2',
    customerId: 'cust3',
    type: StoredValueTxType.RECHARGE,
    amount: 5000,
    balanceAfter: 5000,
    referralPortion: 0,
    note: '开通随心卡',
    createdAt: new Date(Date.now() - 365 * 86400000),
  },
  {
    id: 'svtx3',
    customerId: 'cust3',
    type: StoredValueTxType.REFERRAL_BONUS,
    amount: 800,
    balanceAfter: 5800,
    referralPortion: 800,
    note: '推荐好友消费返现',
    createdAt: new Date(Date.now() - 180 * 86400000),
  },
];

export const mockSettlements: Settlement[] = [
  {
    id: 'settle1',
    shopId: 'shop1',
    customerId: 'cust1',
    customerName: '张三',
    bookingId: 'book1',
    items: [
      { type: 'service', id: 's1', name: '精剪', originalPrice: 68, quantity: 1, discountedPrice: 42.44, total: 42.44 },
      { type: 'product', id: 'p1', name: '防脱洗发水', originalPrice: 168, quantity: 1, discountedPrice: 105.10, total: 105.10, category: ProductCategory.HAIR_CARE },
    ],
    subtotal: 236,
    discountDetail: {
      purchaseVIPDiscount: 0.78,
      storedValueDiscount: 0.8,
      finalDiscount: 0.624,
      purchaseVIPDiscountAmount: 51.92,
      storedValueDiscountAmount: 36.58,
      benefitDiscountAmount: 0,
      discount: 88.5,
    },
    discount: 88.5,
    tax: 0,
    total: 147.54,
    paymentMethod: 'wechat',
    paymentStatus: 'completed',
    usedBenefitIds: [],
    createdAt: new Date(Date.now() - 86400000),
    processedBy: '收银员小王',
  },
  {
    id: 'settle2',
    shopId: 'shop1',
    customerId: 'cust3',
    customerName: '王五',
    items: [
      { type: 'service', id: 's2', name: '烫染套餐', originalPrice: 388, quantity: 1, discountedPrice: 158.30, total: 158.30 },
    ],
    subtotal: 388,
    discountDetail: {
      purchaseVIPDiscount: 0.58,
      storedValueDiscount: 0.7,
      finalDiscount: 0.406,
      purchaseVIPDiscountAmount: 162.96,
      storedValueDiscountAmount: 66.74,
      benefitDiscountAmount: 0,
      discount: 229.7,
    },
    discount: 229.7,
    tax: 0,
    total: 158.3,
    paymentMethod: 'balance',
    paymentStatus: 'completed',
    usedBenefitIds: [],
    createdAt: new Date(Date.now() - 172800000),
    processedBy: '店长',
  },
  {
    id: 'settle3',
    shopId: 'shop1',
    customerId: 'cust5',
    customerName: '孙七',
    items: [
      { type: 'service', id: 's3', name: '护理', originalPrice: 168, quantity: 1, discountedPrice: 95.14, total: 95.14 },
      { type: 'product', id: 'p2', name: '发膜', originalPrice: 128, quantity: 1, discountedPrice: 72.49, total: 72.49, category: ProductCategory.HAIR_CARE },
      { type: 'product', id: 'p3', name: '发胶', originalPrice: 88, quantity: 2, discountedPrice: 99.72, total: 99.72, category: ProductCategory.STYLING },
    ],
    subtotal: 472,
    discountDetail: {
      purchaseVIPDiscount: 0.68,
      storedValueDiscount: 0.85,
      finalDiscount: 0.578,
      purchaseVIPDiscountAmount: 151.04,
      storedValueDiscountAmount: 52.37,
      benefitDiscountAmount: 0,
      discount: 203.41,
    },
    discount: 203.41,
    tax: 0,
    total: 268.59,
    paymentMethod: 'alipay',
    paymentStatus: 'completed',
    usedBenefitIds: [],
    createdAt: new Date(Date.now() - 259200000),
    processedBy: '收银员小王',
  },
];

export const mockSurveys: SatisfactionSurvey[] = [
  {
    id: 'survey1',
    bookingId: 'book1',
    customerId: 'cust1',
    customerName: '张三',
    shopId: 'shop1',
    rating: 5,
    comment: '发型师技术非常好，服务态度也很棒！下次还来！',
    recommended: true,
    createdAt: new Date(Date.now() - 86400000),
  },
  {
    id: 'survey2',
    bookingId: 'book2',
    customerId: 'cust2',
    customerName: '李四',
    shopId: 'shop1',
    rating: 4,
    comment: '整体不错，就是等待时间有点长',
    recommended: true,
    createdAt: new Date(Date.now() - 172800000),
  },
  {
    id: 'survey3',
    bookingId: 'book3',
    customerId: 'cust3',
    customerName: '王五',
    shopId: 'shop1',
    rating: 5,
    comment: '作为股东会员，享受了很好的服务体验',
    recommended: true,
    createdAt: new Date(Date.now() - 259200000),
  },
];

export const mockReferrals: ReferralRecord[] = [
  {
    id: 'ref1',
    referrerId: 'cust1',
    referrerName: '张三',
    referredId: 'cust2',
    referredName: '李四',
    referredPhone: '13900000002',
    bonusAmount: 23.6,
    status: 'paid',
    createdAt: new Date(Date.now() - 30 * 86400000),
    confirmedAt: new Date(Date.now() - 25 * 86400000),
  },
  {
    id: 'ref2',
    referrerId: 'cust3',
    referrerName: '王五',
    referredId: 'cust5',
    referredName: '孙七',
    referredPhone: '13900000005',
    bonusAmount: 31.04,
    status: 'confirmed',
    createdAt: new Date(Date.now() - 20 * 86400000),
    confirmedAt: new Date(Date.now() - 15 * 86400000),
  },
  {
    id: 'ref3',
    referrerId: 'cust1',
    referrerName: '张三',
    referredId: 'cust4',
    referredName: '赵六',
    referredPhone: '13900000004',
    bonusAmount: 21.24,
    status: 'pending',
    createdAt: new Date(Date.now() - 5 * 86400000),
  },
];

export const mockShopReviews: ShopReview[] = [
  {
    id: 'sr1',
    shopId: 'shop1',
    customerId: 'cust1',
    customerName: '张三',
    customerAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face',
    bookingId: 'book1',
    rating: 5,
    serviceRating: 5,
    skillRating: 5,
    environmentRating: 4,
    priceRating: 4,
    comment: '整体服务非常好，发型师技术精湛，环境也很舒适，会推荐给朋友！',
    tags: ['技术好', '服务棒', '环境舒适'],
    reply: '感谢您的好评，我们会继续努力！',
    replyBy: '张店长',
    replyAt: new Date(Date.now() - 80000000),
    isHidden: false,
    createdAt: new Date(Date.now() - 86400000),
  },
  {
    id: 'sr2',
    shopId: 'shop1',
    customerId: 'cust2',
    customerName: '李四',
    customerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face',
    rating: 4,
    serviceRating: 4,
    skillRating: 5,
    environmentRating: 4,
    priceRating: 3,
    comment: '技术不错，就是价格稍微偏高了一点',
    tags: ['技术好', '价格偏高'],
    isHidden: false,
    createdAt: new Date(Date.now() - 3 * 86400000),
  },
  {
    id: 'sr3',
    shopId: 'shop1',
    customerId: 'cust3',
    customerName: '王五',
    customerAvatar: 'https://images.unsplash.com/photo-150703211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face',
    rating: 5,
    serviceRating: 5,
    skillRating: 5,
    environmentRating: 5,
    priceRating: 5,
    comment: '作为老客户，一直很信赖这家店，服务态度好，技术也很专业。',
    tags: ['老客户推荐', '服务好', '技术专业'],
    isHidden: false,
    createdAt: new Date(Date.now() - 7 * 86400000),
  },
];

export const mockStylistReviews: StylistReview[] = [
  {
    id: 'str1',
    shopId: 'shop1',
    stylistId: 'e1',
    stylistName: '李明',
    customerId: 'cust1',
    customerName: '张三',
    customerAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face',
    bookingId: 'book1',
    serviceName: '精剪',
    rating: 5,
    skillRating: 5,
    serviceRating: 5,
    communicationRating: 5,
    comment: '李明老师技术非常好，很懂客户需求，沟通很专业！',
    tags: ['技术精湛', '沟通好', '专业'],
    reply: '谢谢张三的认可，期待下次为您服务！',
    replyAt: new Date(Date.now() - 80000000),
    isHidden: false,
    createdAt: new Date(Date.now() - 86400000),
  },
  {
    id: 'str2',
    shopId: 'shop1',
    stylistId: 'e2',
    stylistName: '王芳',
    customerId: 'cust2',
    customerName: '李四',
    customerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face',
    serviceName: '烫染套餐',
    rating: 5,
    skillRating: 5,
    serviceRating: 4,
    communicationRating: 5,
    comment: '王芳老师做的烫染效果很好，颜色很自然，非常满意！',
    tags: ['烫染效果好', '颜色自然'],
    isHidden: false,
    createdAt: new Date(Date.now() - 3 * 86400000),
  },
  {
    id: 'str3',
    shopId: 'shop1',
    stylistId: 'e1',
    stylistName: '李明',
    customerId: 'cust3',
    customerName: '王五',
    customerAvatar: 'https://images.unsplash.com/photo-150703211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face',
    serviceName: '精剪',
    rating: 5,
    skillRating: 5,
    serviceRating: 5,
    communicationRating: 5,
    comment: '李明老师剪发很仔细，每次都让我很满意！',
    tags: ['细心', '技术好'],
    isHidden: false,
    createdAt: new Date(Date.now() - 2 * 86400000),
  },
  {
    id: 'str4',
    shopId: 'shop1',
    stylistId: 'e3',
    stylistName: '张伟',
    customerId: 'cust5',
    customerName: '孙七',
    customerAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100&fit=crop&crop=face',
    serviceName: '精剪',
    rating: 4,
    skillRating: 4,
    serviceRating: 5,
    communicationRating: 4,
    comment: '张伟老师服务态度很好，剪发也不错！',
    tags: ['服务好'],
    isHidden: false,
    createdAt: new Date(Date.now() - 5 * 86400000),
  },
];

export const mockFollowUps: FollowUpRecord[] = [
  {
    id: 'fu1',
    customerId: 'cust1',
    customerName: '张三',
    shopId: 'shop1',
    followUpBy: 'cs1',
    followUpByName: '刘客服',
    type: 'wechat',
    purpose: 'satisfaction',
    result: 'success',
    rating: 5,
    comment: '客户对上次服务非常满意，已预约下周再次到店。',
    nextAction: '预约确认',
    nextFollowUpAt: new Date(Date.now() + 7 * 86400000),
    bookingId: 'book1',
    createdAt: new Date(Date.now() - 5 * 86400000),
  },
  {
    id: 'fu2',
    customerId: 'cust2',
    customerName: '李四',
    shopId: 'shop1',
    followUpBy: 'cs1',
    followUpByName: '刘客服',
    type: 'phone',
    purpose: 'rebooking',
    result: 'success',
    rating: 4,
    comment: '客户表示会考虑再次到店，已发送优惠券。',
    nextAction: '发送促销信息',
    nextFollowUpAt: new Date(Date.now() + 14 * 86400000),
    createdAt: new Date(Date.now() - 2 * 86400000),
  },
  {
    id: 'fu3',
    customerId: 'cust3',
    customerName: '王五',
    shopId: 'shop1',
    followUpBy: 'mgr1',
    followUpByName: '张店长',
    type: 'visit',
    purpose: 'membership',
    result: 'success',
    rating: 5,
    comment: '股东会员客户，对店铺运营情况反馈很好。',
    nextAction: '定期回访',
    nextFollowUpAt: new Date(Date.now() + 30 * 86400000),
    createdAt: new Date(Date.now() - 1 * 86400000),
  },
  {
    id: 'fu4',
    customerId: 'cust4',
    customerName: '赵六',
    shopId: 'shop1',
    followUpBy: 'cs1',
    followUpByName: '刘客服',
    type: 'sms',
    purpose: 'promotion',
    result: 'pending',
    comment: '新客户，发送了新店活动信息，等待客户回复。',
    nextAction: '等待回复',
    nextFollowUpAt: new Date(Date.now() + 3 * 86400000),
    createdAt: new Date(Date.now() - 1 * 86400000),
  },
  {
    id: 'fu5',
    customerId: 'cust5',
    customerName: '孙七',
    shopId: 'shop1',
    followUpBy: 'cs1',
    followUpByName: '刘客服',
    type: 'wechat',
    purpose: 'satisfaction',
    result: 'success',
    rating: 5,
    comment: '客户对烫染服务非常满意，会推荐朋友来店。',
    createdAt: new Date(Date.now() - 4 * 86400000),
  },
];
